---
name: Build image for Keycloak
run-name: "Image for patched Keycloak ${{ inputs.keycloak-tag }}."

on:
  workflow_dispatch:
    inputs:
      keycloak-tag:
        description: "Keycloak version tag"
        required: true
        default: "26.3.2"
      image-tag-postfix:
        description: "Postfix to add to image tag"
        required: false
        default: ""
      create-release:
        description: "Create or not GitHub release tag. Only applicable to default branch"
        default: false
        required: false
        type: boolean
      tag:
        description: "GitHub tag name to create if `create-release == true`"
        default: "26.3.2-patched"
        required: false

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Create a New Tag
        if: inputs.create-release == 'true' && github.ref_name == github.event.repository.default_branch
        uses: netcracker/qubership-workflow-hub/actions/tag-action@d11baa8a4b42d1a931808c0766ee23eb344c47dd # v2.2.0
        with:
          ref: ${{ github.ref_name }}
          tag-name: ${{ inputs.tag }}
          force-create: ${{ inputs.forceCreate }}
          switch-to-tag: true
          create-release: true
          skip-checkout: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up
        if: inputs.create-release == 'true'
        run: |
          rm -rf ./*

      - name: Checkout Keycloak source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.keycloak-tag }}
          repository: keycloak/keycloak

      - name: Checkout this repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./keycloak-patches

      - name: Apply patches
        run: |
          cd ${GITHUB_WORKSPACE}
          for p in ./keycloak-patches/keycloak-patches/${{ inputs.keycloak-tag }}/*.patch; do
            echo "Applying $p…"
            git apply -p1 --ignore-space-change --ignore-whitespace "$p"
          done
          rm -rf ./keycloak-patches

      - name: Set up Maven
        uses: stCarolas/setup-maven@12eb41b233df95d49b0c11fc1b5bc8312e5d4ce0 # v5.1
        with:
          maven-version: 3.9.8

      - name: build
        uses: ./.github/actions/build-keycloak
        with:
          upload-m2-repo: true
          upload-dist: true
          workspace: keycloak-src

      - name: "Upload artifacts"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: keycloak
          path: ./quarkus/dist/target/keycloak-*.tar.gz

      - name: "Upload assets"
        if: inputs.create-release == 'true' && github.ref_name == github.event.repository.default_branch
        uses: netcracker/qubership-workflow-hub/actions/assets-action@d11baa8a4b42d1a931808c0766ee23eb344c47dd # v2.2.0
        with:
          tag: ${{ inputs.tag }}
          item-path: ./quarkus/dist/target/keycloak-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image preparation
        run: |
          version=$(ls quarkus/dist/target/keycloak-*.tar.gz | cut -d'/' -f4 | sed "s/keycloak-\(.*\).tar.gz/\1/")
          echo "keycloak_version=${version,,}" >> $GITHUB_ENV
          cp $GITHUB_WORKSPACE/quarkus/dist/target/keycloak-*.tar.gz $GITHUB_WORKSPACE/quarkus/container
          echo "keycloak_tar=`basename $(ls quarkus/container/keycloak-*.tar.gz)`" >> $GITHUB_ENV
          if [ "${{ github.event.repository.default_branch }}" != "${{ github.ref_name }}" ]; then
            image_tag=${version,,}-${GITHUB_REF_NAME//\//_}${{inputs.image-tag-postfix}}
          else
            image_tag=${version,,}${{inputs.image-tag-postfix}}
          fi
          echo "image_tag=${image_tag,,}" >> $GITHUB_ENV
        
      - name: Login to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Set lowercase repository owner
        run: echo "repo_owner_lc=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Debug tag
        run: echo "ghcr.io/${{ env.repo_owner_lc }}/${{ github.event.repository.name }}:${{ env.image_tag }}"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          provenance: false
          context: ${{ github.workspace }}/quarkus/container
          file: ${{ github.workspace }}/quarkus/container/Dockerfile
          build-args: |
            KEYCLOAK_DIST=${{ env.keycloak_tar }}
          push: "true"
          tags: |
            ghcr.io/${{ env.repo_owner_lc }}/${{ github.event.repository.name }}:${{ env.image_tag }}
          platforms: linux/amd64
          github-token: ${{ secrets.GITHUB_TOKEN }}
